//App States
export const ADD_PROPERTY_REQUEST = 'ADD_PROPERTY_REQUEST';
export const ADD_PROPERTY_SUCCESS = 'ADD_PROPERTY_SUCCESS';
export const ADD_PROPERTY_FAILURE = 'ADD_PROPERTY_FAILURE';
//Set Current Addres
export const SET_ADDRESS_REQUEST = 'SET_ADDRESS_REQUEST';
export const SET_ADDRESS_SUCCESS = 'SET_ADDRESS_SUCCESS';

//  Set Buyer Data
export const ADD_BUYER_DATA_REQUEST = 'ADD_BUYER_DATA_REQUEST';
export const ADD_BUYER_DATA_SUCCESS = 'ADD_BUYER_DATA_SUCCESS';

//  Get Buyer Data
export const GET_BUYER_DATA_REQUEST = 'GET_BUYER_DATA_REQUEST';
export const GET_BUYER_DATA_SUCCESS = 'GET_BUYER_DATA_SUCCESS';
export const GET_BUYER_DATA_FAILURE = 'GET_BUYER_DATA_FAILURE';

//Get All Properties
export const GET_ALL_PROPERTIES_REQUEST = 'GET_ALL_PROPERTIES_REQUEST';
export const GET_ALL_PROPERTIES_SUCCESS = 'GET_ALL_PROPERTIES_SUCCESS';
export const GET_ALL_PROPERTIES_FAILURE = 'GET_ALL_PROPERTIES_FAILURE';

//Get Recent Properties
export const GET_RECENT_PROPERTIES_REQUEST = 'GET_RECENT_PROPERTIES_REQUEST';
export const GET_RECENT_PROPERTIES_SUCCESS = 'GET_RECENT_PROPERTIES_SUCCESS';
export const GET_RECENT_PROPERTIES_FAILURE = 'GET_RECENT_PROPERTIES_FAILURE';

//Get FILTERED all Properties
export const GET_FILTERED_PROPERTIES_REQUEST =
  'GET_FILTERED_PROPERTIES_REQUEST';
export const GET_FILTERED_PROPERTIES_SUCCESS =
  'GET_FILTERED_PROPERTIES_SUCCESS';
export const GET_FILTERED_PROPERTIES_FAILURE =
  'GET_FILTERED_PROPERTIES_FAILURE';

//Types for Login
export const LOGIN_REQUEST_REQUEST = 'LOGIN_REQUEST_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE';
//Types for Logout
export const LOGOUT_REQUEST_REQUEST = 'LOGOUT_REQUEST_REQUEST';
export const LOGOUT_REQUEST_SUCCESS = 'LOGOUT_REQUEST_SUCCESS';
export const LOGOUT_REQUEST_FAILURE = 'LOGOUT_REQUEST_FAILURE';
//Types for Social Login
export const SOCIAL_LOGIN_REQUEST = 'SOCIAL_LOGIN_REQUEST';
export const SOCIAL_LOGIN_REQUEST_SUCCESS = 'SOCIAL_LOGIN_REQUEST_SUCCESS';
export const SOCIAL_LOGIN_REQUEST_FAILURE = 'SOCIAL_LOGIN_REQUEST_FAILURE';
//Types for Sign up
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

//Types for Crate Support Closure
export const SET_SUPPORT_INFO_REQUEST = 'SET_SUPPORT_INFO_REQUEST';
export const SET_SUPPORT_INFO_SUCCESS = 'SET_SUPPORT_INFO_SUCCESS';

//Types for OTP Verification
export const OTP_VERIFY_REQUEST = 'OTP_VERIFY_REQUEST';
export const OTP_VERIFY_SUCCESS = 'OTP_VERIFY_SUCCESS';
export const OTP_VERIFY_FAILURE = 'OTP_VERIFY_FAILURE';

//Types for  forgot password
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

//Types for reset password
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

//Types for User Type
export const USER_TYPE_REQUEST = 'USER_TYPE_REQUEST';
export const USER_TYPE_SUCCESS = 'USER_TYPE_SUCCESS';
export const USER_TYPE_FAILURE = 'USER_TYPE_FAILURE';

//Types for  Resend OTP
export const RESEND_OTP_REQUEST = 'RESEND_OTP_REQUEST';
export const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS';
export const RESEND_OTP_FAILURE = 'RESEND_OTP_FAILURE';

//Types for  Add Additional Info
export const ADD_ADDITIONAL_INFO_REQUEST = 'ADD_ADDITIONAL_INFO_REQUEST';
export const ADD_ADDITIONAL_INFO_SUCCESS = 'ADD_ADDITIONAL_INFO_SUCCESS';
export const ADD_ADDITIONAL_INFO_FAILURE = 'ADD_ADDITIONAL_INFO_FAILURE';

//Types for Settings

// get profile info req
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

// update profile info req
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

//Get CARD LIST
export const GET_CARD_LIST_REQUEST = 'GET_CARD_LIST_REQUEST';
export const GET_CARD_LIST_SUCCESS = 'GET_CARD_LIST_SUCCESS';
export const GET_CARD_LIST_FAILURE = 'GET_CARD_LIST_FAILURE';

//Add Default Card
export const ADD_DEFAULT_CARD_REQUEST = 'ADD_DEFAULT_CARD_REQUEST';
export const ADD_DEFAULT_CARD_SUCCESS = 'ADD_DEFAULT_CARD_SUCCESS';
export const ADD_DEFAULT_CARD_FAILURE = 'ADD_DEFAULT_CARD_FAILURE';

//Get Default Card
export const GET_DEFAULT_CARD_REQUEST = 'GET_DEFAULT_CARD_REQUEST';
export const GET_DEFAULT_CARD_SUCCESS = 'GET_DEFAULT_CARD_SUCCESS';
export const GET_DEFAULT_CARD_FAILURE = 'GET_DEFAULT_CARD_FAILURE';

//ADD CARD
export const ADD_CARD_REQUEST = 'ADD_CARD_REQUEST';
export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS';
export const ADD_CARD_FAILURE = 'ADD_CARD_FAILURE';
//Deleted Card
export const DELETE_CARD_REQUEST = 'DELETE_CARD_REQUEST';
export const DELETE_CARD_SUCCESS = 'DELETE_CARD_SUCCESS';
export const DELETE_CARD_FAILURE = 'DELETE_CARD_FAILURE';
//Edit card
export const EDIT_CARD_REQUEST = 'EDIT_CARD_REQUEST';
export const EDIT_CARD_SUCCESS = 'EDIT_CARD_SUCCESS';
export const EDIT_CARD_FAILURE = 'EDIT_CARD_FAILURE';
//Pay With Debit
export const PAY_WITH_DEBIT_REQUEST = 'PAY_WITH_DEBIT_REQUEST';
export const PAY_WITH_DEBIT_SUCCESS = 'PAY_WITH_DEBIT_SUCCESS';
export const PAY_WITH_DEBIT_FAILURE = 'PAY_WITH_DEBIT_FAILURE';

//Pay With Google
export const PAY_WITH_SOCIAL_REQUEST = 'PAY_WITH_SOCIAL_REQUEST';
export const PAY_WITH_SOCIAL_SUCCESS = 'PAY_WITH_SOCIAL_SUCCESS';
export const PAY_WITH_SOCIAL_FAILURE = 'PAY_WITH_SOCIAL_FAILURE';

//Static pages
export const STATIC_PAGES_REQUEST = 'STATIC_PAGES_REQUEST';
export const STATIC_PAGES_SUCCESS = 'STATIC_PAGES_SUCCESS';
export const STATIC_PAGES_FAILURE = 'STATIC_PAGES_FAILURE';

//Get Queries
export const GET_QUERIES_REQUEST = 'GET_QUERIES_REQUEST';
export const GET_QUERIES_SUCCESS = 'GET_QUERIES_SUCCESS';
export const GET_QUERIES_FAILURE = 'GET_QUERIES_FAILURE';

//Add Query
export const ADD_QUERY_REQUEST = 'ADD_QUERY_REQUEST';
export const ADD_QUERY_SUCCESS = 'ADD_QUERY_SUCCESS';
export const ADD_QUERY_FAILURE = 'ADD_QUERY_FAILURE';

//Types for Bookmarks

// add to bookmarks
export const ADD_TO_BOOKMARKS_REQUEST = 'ADD_TO_BOOKMARKS_REQUEST';
export const ADD_TO_BOOKMARKS_SUCCESS = 'ADD_TO_BOOKMARKS_SUCCESS';
export const ADD_TO_BOOKMARKS_FAILURE = 'ADD_TO_BOOKMARKS_FAILURE';

// get all bookmarks
export const GET_BOOKMARKS_REQUEST = 'GET_BOOKMARKS_REQUEST';
export const GET_BOOKMARKS_SUCCESS = 'GET_BOOKMARKS_SUCCESS';
export const GET_BOOKMARKS_FAILURE = 'GET_BOOKMARKS_FAILURE';

// get filtered bookmarks
export const FILTER_BOOKMARKS_REQUEST = 'FILTER_BOOKMARKS_REQUEST';
export const FILTER_BOOKMARKS_SUCCESS = 'FILTER_BOOKMARKS_SUCCESS';
export const FILTER_BOOKMARKS_FAILURE = 'FILTER_BOOKMARKS_FAILURE';

// remove from bookmarks list
export const REMOVE_BOOKMARK_REQUEST = 'REMOVE_BOOKMARK_REQUEST';
export const REMOVE_BOOKMARK_SUCCESS = 'REMOVE_BOOKMARK_SUCCESS';
export const REMOVE_BOOKMARK_FAILURE = 'REMOVE_BOOKMARK_FAILURE';

//*************************Support User Types */
// remove from bookmarks list
export const SUPPORT_USER_REQUEST = 'SUPPORT_USER_REQUEST';
export const SUPPORT_USER_SUCCESS = 'SUPPORT_USER_SUCCESS';
export const SUPPORT_USER_FAILURE = 'SUPPORT_USER_FAILURE';

// Selected Support User
export const SELECTED_SUPPORT_USER_REQUEST = 'SELECTED_SUPPORT_USER_REQUEST';
export const SELECTED_SUPPORT_USER_SUCCESS = 'SELECTED_SUPPORT_USER_SUCCESS';
export const SELECTED_SUPPORT_USER_FAILURE = 'SELECTED_SUPPORT_USER_FAILURE';

// **************** Conversation Types */
export const CREATE_CONVERSATION_REQUEST = 'CREATE_CONVERSATION_REQUEST';
export const CREATE_CONVERSATION_SUCCESS = 'CREATE_CONVERSATION_SUCCESS';
export const CREATE_CONVERSATION_FAILURE = 'CREATE_CONVERSATION_FAILURE';

export const GET_CONVERSATION_LIST_REQUEST = 'GET_CONVERSATION_LIST_REQUEST';
export const GET_CONVERSATION_LIST_SUCCESS = 'GET_CONVERSATION_LIST_SUCCESS';
export const GET_CONVERSATION_LIST_FAILURE = 'GET_CONVERSATION_LIST_FAILURE';

export const DELETE_CONVERSATION_REQUEST = 'DELETE_CONVERSATION_REQUEST';
export const DELETE_CONVERSATION_SUCCESS = 'DELETE_CONVERSATION_SUCCESS';
export const DELETE_CONVERSATION_FAILURE = 'DELETE_CONVERSATION_FAILURE';

export const GET_ALL_MESSAGES_REQUEST = 'GET_ALL_MESSAGES_REQUEST';
export const GET_ALL_MESSAGES_SUCCESS = 'GET_ALL_MESSAGES_SUCCESS';
export const GET_ALL_MESSAGES_FAILURE = 'GET_ALL_MESSAGES_FAILURE';

export const READ_MESSAGES_REQUEST = 'READ_MESSAGES_REQUEST';
export const READ_MESSAGES_SUCCESS = 'READ_MESSAGES_SUCCESS';
export const READ_MESSAGES_FAILURE = 'READ_MESSAGES_FAILURE';

export const REPORT_USER_REQUEST = 'REPORT_USER_REQUEST';
export const REPORT_USER_SUCCESS = 'REPORT_USER_SUCCESS';
export const REPORT_USER_FAILURE = 'REPORT_USER_FAILURE';

export const BLOCK_USER_REQUEST = 'BLOCK_USER_REQUEST';
export const BLOCK_USER_SUCCESS = 'BLOCK_USER_SUCCESS';
export const BLOCK_USER_FAILURE = 'BLOCK_USER_FAILURE';

export const GET_BLOCK_USER_LIST_REQUEST = 'GET_BLOCK_USER_LIST_REQUEST';
export const GET_BLOCK_USER_LIST_SUCCESS = 'GET_BLOCK_USER_LIST_SUCCESS';
export const GET_BLOCK_USER_LIST_FAILURE = 'GET_BLOCK_USER_LIST_FAILURE';

export const UNBLOCK_USER_REQUEST = 'UNBLOCK_USER_REQUEST';
export const UNBLOCK_USER_SUCCESS = 'UNBLOCK_USER_SUCCESS';
export const UNBLOCK_USER_FAILURE = 'UNBLOCK_USER_FAILURE';

export const GET_NOTIFICATION_LIST_REQUEST = 'GET_NOTIFICATION_LIST_REQUEST';
export const GET_NOTIFICATION_LIST_SUCCESS = 'GET_NOTIFICATION_LIST_SUCCESS';
export const GET_NOTIFICATION_LIST_FAILURE = 'GET_NOTIFICATION_LIST_FAILURE';

export const SEND_FCM_REQUEST = 'SEND_FCM_REQUEST';
export const SEND_FCM_SUCCESS = 'SEND_FCM_SUCCESS';
export const SEND_FCM_FAILURE = 'SEND_FCM_FAILURE';
